
version: '3.8'

services:
  php_container:
    build:
      context: etc/infrastructure
      dockerfile: php.Dockerfile
    container_name: php_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9501
    expose:
      - 9001
